### ISSUE TITLE
How to construct a prompt to LLM for each issue？

### ISSUE THREAD

**Issue by Smith-xuan** [CoderEval/CoderEval#11]
I observe that the json table entries you construct for each question have the three main attributes input, signature, and docstring. May I ask how you guys construct the prompt when you have the LLMs generate the answers to the questions? Is it simply giving the LLMs all the main information as a prompt in the following format: "[prompt]Input:... \n Signature:... \n Docstring:..." Or is it some other format?
I hope you can answer my query, thank you very much!

**Comment by monkeyhjy** [comment]
@Smith-xuan 
I have this question too, and I try another command like this to solve the problem: 
**docker import ./Codereval.tar your_image_name**
