### ISSUE TITLE
open source test code?

### ISSUE THREAD

**Issue by felixhao28** [CoderEval/CoderEval#2]
Will the code used to inject the generated code into the original project be released? Along with the hand-written tests? And the scripts to run the tests and collect results?

**Comment by yh1105** [comment]
Since the particularity of test cases in CoderEval, test cases are embedded in complete test code of the project. Due to the restricted regulations in our corporate company, we can't publish it temporarily now, but we will provide API service soon.

**Comment by felixhao28** [comment]
Thanks for the reply. May I know which company this code belongs to?

**Comment by yh1105** [comment]
Sure, Huawe company.
Thanks for your interest!

**Comment by ajdesh2000** [comment]
Hi, any ETA on when the API service will be released? Additionally, is it possible to provide the commit ids of the repos used?

**Comment by yh1105** [comment]
Thank you for your interest. We will update this repository within half a month and release all test cases and execution environments.

**Comment by ajdesh2000** [comment]
Hi, thanks, just wanted to check if the release happened

**Comment by yh1105** [comment]
@ajdesh2000 Hi, to prepare the ''Artifact Evaluation Track'' for CoderEval accepted in ICSE, we are restructuring the entire evaluation platform to make it execute faster and more reliably (it is expected to take another week to fully prepare). We originally planned to open source together when we were ready. If you are in a hurry, you can first give me your email (send an email to yh0315@pku.edu.cn ）I will send you the current version of CoderEval first.
