### ISSUE TITLE
Input prompt to models

### ISSUE THREAD

**Issue by aksh555** [CoderEval/CoderEval#3]
Hi, thanks for creating this dataset!
I would like to know what is the prompt you used to generate the code using `docstring` and `human_abel` respectively in table 5. Do you utilize `all_context` for code generation in Table 3?

The raw and human_label json files seem to be using the same docstring input during generation

**Comment by yh1105** [comment]
Thanks for your interest!
We do not use the all_context information in our experiments, all experiments in our paper use only original docstring, human_labeled docstring, and function signature. We hope the all_context information is valuable for the research community, and we will study the impact of all_context information on code generation task in our future work.

**Comment by aksh555** [comment]
Thanks for clarifying, so the prompt is either docstring + function signature or human_label + docstring?

**Comment by yh1105** [comment]
Yes, the results in Table 3 are using docstring + function signature, and the results of human_label + docstring are shown in Table 5.
