### ISSUE TITLE
Missing Language Model Inference Scripts in Docker Files

### ISSUE THREAD

**Issue by Paper-blue** [CoderEval/CoderEval#5]
I'm so pleased to see your team could provide the Docker profile. However, during my review of the source code, I did not find scripts for calling or inferring various large language models (in short, scripts for generating `Raw_Input.jsonl`). 

I wonder if they have not yet been updated to the Docker files or if they exist in another path? If not yet updated, could you please inform me of the update time? 

Once again, thank you for your team's contribution.

**Comment by yh1105** [comment]
@Paper-blue Thanks for your interest!
I just uploaded CoderEval's input in the model inference stage. Due to the different inference scripts for different models, you can write them yourself (the model inference scripts are all open-source and not complex in their respective repositories).

**Comment by Paper-blue** [comment]
Thank you for your timely reply and update, which is of great help!
